### ISSUE TITLE
Transaksi gagal tidak bisa memilih payment method

### ISSUE THREAD

**Issue by drxchi** [apinprastya/flutrans#12]
Setiap melakukan pembayaran selalu langsung muncul 
![341194](https://user-images.githubusercontent.com/39695883/89991939-c671fa00-dcae-11ea-9677-679896c58a78.jpg)

**Comment by apinprastya** [comment]
Kesalahan bukan pada library ini. Silakan check console untuk mengetahui errornya apa.

**Comment by anvarisy** [comment]
That cause your server return a wrong value.
server should return snap code, and url.
this library need 2 value in one json to create midtrans fragmentactivity
