### ISSUE TITLE
Sample Back End

### ISSUE THREAD

**Issue by anvarisy** [apinprastya/flutrans#13]
Can you send me sample of the server side.

**Comment by apinprastya** [comment]
just google it

**Comment by anvarisy** [comment]
i've done with it.
maybe you must give more information to add
midtrans activity in android manifest.
cause if just follow your instructions, it will return error when select
channel transaction.
Good at all for library thank you

Anvarisy

**Comment by apinprastya** [comment]
What error you have? And how you fixed it? Please share here.

**Comment by anvarisy** [comment]
My Error ?
Activity not found, that cause midtrans activity not registered by default in flutter so we must registered manually but that was solved easyly

**Comment by apinprastya** [comment]
I am not sure about the error, maybe that is a new requirement for a 'new flutter'
