### ISSUE TITLE
FlutransPlugin - startActivity()

### ISSUE THREAD

**Issue by rahmansaleh** [apinprastya/flutrans#2]
This error occurred when I tried this library.

''D/FlutransPlugin(13880): ERROR Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?'' 

I tried editing your code in my local folder but I couldn't finish it. Please your help

**Comment by WillyAdrianus** [comment]
I have same issue.. Can someone share how to fix this??

**Comment by rifal-klikeat** [comment]
i have same issue, please help

**Comment by apinprastya** [comment]
If you able to build example from this repo then I can not help you.
You have to make the example has error like yours, then maybe I can help.

**Comment by rifal-klikeat** [comment]
thanks, i fixed with downgrade the androidX and androidSDK
thanks
