### ISSUE TITLE
on ios not work, only return "finally"

### ISSUE THREAD

**Issue by rifal-klikeat** [apinprastya/flutrans#4]
hei, on IOS when makePayment, its just return finally on console, no effect, can you help me?

**Comment by rifal-klikeat** [comment]
Email error notife
transaction_details.gross_amount harus sama atau lebih besar dari 0.01
transaction_details.gross_amount is not equal to the sum of item_details
customer_details.billing_address.country_code jumlah karakter salah (seharusnya 3 karakter)
customer_details.shipping_address.country_code jumlah karakter salah (seharusnya 3 karakter)

On my gross amount minus - value
Its work fine on android, but on ios return finally and get that email

**Comment by raymondsugiarto** [comment]
i have same issue, but there is email error and flutter never hit my server.
it just return finally on console.

how to debug it and fixed it?
please help
