### ISSUE TITLE
URL BASE

### ISSUE THREAD

**Issue by Shuusan** [apinprastya/flutrans#8]
what is this?how can i find my URL BASE for sandbox mode?

**Comment by apinprastya** [comment]
Url base itu alamat backend Anda yang dipakai untuk ngurisin pembayaran. Silakan pelajari dulu gimana cara kerja midtrans.
Note: saya bukan pegawai midtrans, jadi silakan meminta bantuan midtrans untuk implementasi di project Anda.

**Comment by arieffajargemilang** [comment]
hapus ajah ini lib. ada oeng tanya malah ngegas.. 🤣🤣

**Comment by apinprastya** [comment]
@arieffajargemilang : ngegas atau enggak tergantung keadaan emosi pembacanya sih kalau menurut saya.
Saya membuat lib ini sebenernya untuk saya sendiri, saya hanya share aja, mungkin bisa membantu orang lain. Kalau @arieffajargemilang tidak cocok bisa membuat lib sendiri terus silakan di publish.

**Comment by arieffajargemilang** [comment]
udh bikin kok dan private karna buat pribadi.. klo buat pribadi gk perlu public spertiny.. yg d public harusny siap tanggu g jawab sma apa yg d tulis.

**Comment by apinprastya** [comment]
@arieffajargemilang itu mah aturan Anda sendiri. Kalau udah bikin sendiri ngapain juga Anda kemari? Terus nyuruh saya ngapus lib ini? 
Toh sebenernya yang seharusnya bikin lib ini orang midtrans langsung karena dia yang membuat midtrans dan memang digaji untuk support programmer yang mau implementasi midtrans.
Enggak semua orang kayak Anda bisa nulis library sendiri, kadang orang datang ke lib saya cuma mau lihat gimana cara bikinnya, ngefork lib ini terus dipakai internal dia.

**Comment by didikz** [comment]
friendly reminder mas @arieffajargemilang open source itu spiritnya kolaborasi dan berkontribusi untuk bisa membuat proyek-proyek open source bisa jadi lebih baik. Jika ada yang kurang dari library ini silahkan ajukan PR di bagian mana yang menurut anda bisa di-improve bukan malah nyuruh yang punya repo untuk hapus repo.

saya kirim PR untuk update readme nya agar lebih bisa dimengerti dan menghindari kebingungan buat pengguna di masa mendatang. cc mas @apinprastya
