### ISSUE TITLE
Always redirected to Production

### ISSUE THREAD

**Issue by felangga** [apinprastya/flutrans#9]
I'm setting the BASE URL as sandbox url. But when I got the token, the library check it with Production URL. How to fix this ?

**Comment by apinprastya** [comment]
This library does not support switching sandbox or production for Android (IOS does support).
Easier way is checkout this library to you local drive, and edit the build.gradle to use sandbox dependency, point the fluttrans library to that folder.

**Comment by felangga** [comment]
Ok it's fixed
